# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNn7zjGjWecqCWOhmsk9Oe8QpRnnC3qv
"""

import streamlit as st
import pandas as pd
from io import BytesIO

# Импортируем функцию из твоего скрипта
from extract_process_hide import process_excel

st.title("Обработка Excel — этап 1")

uploaded_file = st.file_uploader("Загрузите Excel-файл", type=["xlsx", "xls"])

if uploaded_file:
    if st.button("Обработать этап 1"):
        # Считываем Excel-файл
        df = pd.read_excel(uploaded_file)

        # Вызываем твою функцию без изменений!
        df = process_excel(df)

        st.write("Этап 1 завершён!")
        st.dataframe(df)

        # Скачать результат
        output = BytesIO()
        df.to_excel(output, index=False)
        output.seek(0)
        st.download_button(
            label="Скачать результат",
            data=output,
            file_name="result_etap1.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
